extends Node

var world:={
	"N.EU":{
		"tile_hp":1,
		"starting_position":Vector2i(13,10),
		"ending_position":Vector2i(16,13),
		"snake_amount":2,
		"location_index":0
		
	},
	"C.AS":{
		"tile_hp":2,
		"starting_position":Vector2i(12,10),
		"ending_position":Vector2i(17,13),
		"snake_amount":2,
		"location_index":1
	},
	"E.EU":{
		"tile_hp":3,
		"starting_position":Vector2i(12,10),
		"ending_position":Vector2i(17,14),
		"snake_amount":2,
		"location_index":2
	},
	"N.AM":{
		"tile_hp":4,
		"starting_position":Vector2i(11,10),
		"ending_position":Vector2i(18,14),
		"snake_amount":2,
		"location_index":3
	},
	"W.EU":{
		"tile_hp":5,
		"starting_position":Vector2i(10,10),
		"ending_position":Vector2i(19,14),
		"snake_amount":2,
		"location_index":4
	},
	"E.AS":{
		"tile_hp":6,
		"starting_position":Vector2i(9,10),
		"ending_position":Vector2i(20,14),
		"snake_amount":2,
		"location_index":5
	},
	"S.EU":{
		"tile_hp":7,
		"starting_position":Vector2i(9,9),
		"ending_position":Vector2i(20,14),
		"snake_amount":2,
		"location_index":6
	},
	"N.AF":{
		"tile_hp":8,
		"starting_position":Vector2i(8,9),
		"ending_position":Vector2i(21,14),
		"snake_amount":2,
		"location_index":7
	},
	"W.AS":{
		"tile_hp":9,
		"starting_position":Vector2i(7,9),
		"ending_position":Vector2i(22,14),
		"snake_amount":2,
		"location_index":8
	},
	"A.NZ":{
		"tile_hp":10,
		"starting_position":Vector2i(7,9),
		"ending_position":Vector2i(22,15),
		"snake_amount":2,
		"location_index":9
	},
	"S.AF":{
		"tile_hp":11,
		"starting_position":Vector2i(6,9),
		"ending_position":Vector2i(23,15),
		"snake_amount":2,
		"location_index":10
	},
	"L.AM":{
		"tile_hp":12,
		"starting_position":Vector2i(6,8),
		"ending_position":Vector2i(23,15),
		"snake_amount":2,
		"location_index":11
	},
	"CARI":{
		"tile_hp":13,
		"starting_position":Vector2i(5,8),
		"ending_position":Vector2i(24,15),
		"snake_amount":2,
		"location_index":12
	},
	"POLY":{
		"tile_hp":14,
		"starting_position":Vector2i(4,8),
		"ending_position":Vector2i(25,15),
		"snake_amount":2,
		"location_index":13
	},
	"S.AS":{
		"tile_hp":15,
		"starting_position":Vector2i(4,7),
		"ending_position":Vector2i(25,15),
		"snake_amount":2,
		"location_index":14
	},
	"SE.AS":{
		"tile_hp":16,
		"starting_position":Vector2i(3,7),
		"ending_position":Vector2i(26,15),
		"snake_amount":2,
		"location_index":15
	},
	"MELA":{
		"tile_hp":17,
		"starting_position":Vector2i(3,6),
		"ending_position":Vector2i(26,15),
		"snake_amount":2,
		"location_index":16
	},
	"MICR":{
		"tile_hp":18,
		"starting_position":Vector2i(2,6),
		"ending_position":Vector2i(27,15),
		"snake_amount":2,
		"location_index":17
	},
	"Platform":{
		"tile_hp":19,
		"starting_position":Vector2i(1,6),
		"ending_position":Vector2i(28,15),
		"snake_amount":1,
		"location_index":18
	},
	"Engine":{
		"tile_hp":20,
		"starting_position":Vector2i(1,6),
		"ending_position":Vector2i(28,15),
		"snake_amount":1,
		"location_index":19
	},
	"Body":{
		"tile_hp":21,
		"starting_position":Vector2i(1,6),
		"ending_position":Vector2i(28,15),
		"snake_amount":1,
		"location_index":20
	},
	"Head":{
		"tile_hp":22,
		"starting_position":Vector2i(1,6),
		"ending_position":Vector2i(28,15),
		"snake_amount":1,
		"location_index":21
	},
	"Fuel":{
		"tile_hp":23,
		"starting_position":Vector2i(1,6),
		"ending_position":Vector2i(28,15),
		"snake_amount":1,
		"location_index":22
	}
}
